star_wars/people/urls.py
from django.urls import path

from . import views


app_name = 'people'


urlpatterns = [
    path('dataset', views.DatasetView.as_view(), name='datasets'),
    path('fetch', views.fetch, name='fetch'),
    path('list/<int:id>', views.PersonView.as_view(), name='list'),
    path(
        'value-count/<int:id>',
        views.PersonCountView.as_view(),
        name='value_count',
    ),
]

star_wars/star_wars/urls.py
from django.urls import include, path
from people import views


urlpatterns = [
    path('', views.DatasetView.as_view(), name='datasets'),
    path('people/', include('people.urls')),
]

star_wars/people/models.py
import petl
from django.db import models


class Dataset(models.Model):
    name = models.CharField(max_length=64)
    file = models.FileField()
    created = models.DateTimeField(auto_now_add=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.table = petl.fromcsv(self.file.name)

    @property
    def header(self):
        # TODO: investigate why we can't get headers without rowslicing O_o
        return self.table.rowslice(0, 0).header()

    @property
    def records(self):
        return self.table.records()

    def slice(self, start, end):
        return self.table.rowslice(start, end)

    def aggregate(self, keys, aggregation_fn):
        # TODO: investigate, why keys can't be a single value list
        keys = keys[0] if len(keys) == 1 else keys
        return self.table.aggregate(key=keys, aggregation=aggregation_fn)

star_wars/people/views.py
import os
import functools
from urllib.parse import urlencode

from django.urls import reverse
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, TemplateView

from . import models
from .data_providers import swapi


def people_to_csv(url, transform_fn):
    """
    Stores data found at `url` calling `transform_fn` on each item.
    """
    page = swapi.fetch_json(url)
    filename = "{}.csv".format(timezone.now().isoformat())
    csv_path = os.path.join(settings.PEOPLE_CSV_FILE_PATH, filename)
    all_people = swapi.iterate_items(page)
    transformed = map(transform_fn, all_people)
    swapi.items_to_csv(transformed, csv_path)
    return filename, csv_path


class DatasetView(ListView):
    model = models.Dataset
    context_object_name = 'datasets'
    ordering = ['-created']


def fetch(request):
    try:
        homeworld_map = swapi.homeworld_map(settings.SWAPI_PLANET_URL)
        name, csv_path = people_to_csv(
            settings.SWAPI_PEOPLE_URL,
            # TODO: simplifiy it, this partial could be dropped
            functools.partial(
                swapi.transform_person_data, homeworld_map=homeworld_map
            )
        )
    except Exception as e:
        data = {
            'error': "Couldn't fetch the latest data set",
            'object': {},
        }
    else:
        dataset, _ = models.Dataset.objects.get_or_create(
            name=name, file=csv_path,
        )
        data = {
            'error': "",
            'object': {},
        }
    return JsonResponse(data)


class PersonView(TemplateView):
    template_name = 'people/person_list.html'

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)

        start = int(self.request.GET.get('start', 0))
        end = int(self.request.GET.get('end', settings.PEOPLE_PAGE_COUNT))
        end_next = int(end) + settings.PEOPLE_PAGE_COUNT
        dataset = get_object_or_404(models.Dataset, pk=self.kwargs.get('id'))

        if end_next < dataset.table.len():
            kwargs['load_more_url'] = "{}?{}".format(
                reverse('people:list', args=(self.kwargs['id'],)),
                urlencode({'start': start, 'end': end_next}),
            )
        else:
            kwargs['load_more_url'] = None

        dataset.table = dataset.slice(start, end)
        kwargs['dataset'] = dataset
        return kwargs


class PersonCountView(TemplateView):
    template_name = 'people/grouped_people.html'

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        dataset = get_object_or_404(models.Dataset, pk=self.kwargs.get('id'))
        kwargs['group_cols'] = {
            h: h in self.request.GET.getlist('groupCol') for h in dataset.header
        }
        picked_cols = [k for k, v in kwargs['group_cols'].items() if v]
        if picked_cols:
            dataset.table = dataset.aggregate(picked_cols, len)
            dataset.table = dataset.table.rename('value', 'Count')

        kwargs['dataset'] = dataset
        return kwargs

star_wars/people/templates/people/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>{% block title %}My amazing site{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>

        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'people:datasets' %}">Star Wars Explorer</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'people:datasets' %}">Data sets</a>
              </li>
            </ul>
          </div>
        </nav>
        {% endblock %}


        <div class="container">
        {% block content %}{% endblock %}
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        <script>
        {% block script %}
        {% endblock %}
        </script>
    </body>
</html>

star_wars/people/templates/people/dataset_list.html
{% extends "people/base.html" %}

{% block title %} People Data Sets {% endblock %}

{% block content %}
<h1>Data sets</h1>
<button id="fetch-button" type="button" class="btn btn-primary">Fetch</button>

<ul id="dataset-container" class="list-group">
{% for dataset in datasets %}
  <li class="list-group-item">
    <a href="{% url 'people:list' dataset.id %}">{{ dataset.created }}</a>
  </li>
{% empty %}
  <li id="empty-list-msg" class="list-group-item">Sorry, no datasets in this list.</li>
{% endfor %}
</ul>

{% endblock %}


{% block script %}

$(document).ready(function() {
  $("#fetch-button").click(function() {
    var data = {
      'csrfmiddlewaretoken': "{{ csrf_token }}"
    };
    $("#fetch-button").prop('disabled', true);
    var jqxhr = $.post("{% url 'people:fetch' %}", data, function(data) {
      if (data.error == '') {
        location.reload();
      } else {
        alert(data.error);
      }
    })
    .fail(function() {
      alert("An error occured, try later.");
    })
    .always(function() {
      $("#fetch-button").prop('disabled', false);
    });
  });
});

{% endblock %}

star_wars/people/templates/people/grouped_people.html
{% extends "people/base.html" %}

{% block title %} People Data Sets {% endblock %}

{% block content %}

<h1><a href="{% url 'people:list' dataset.id %}">{{dataset.created}}</a></h1>

<form id="groupForm" action="{% url 'people:value_count' dataset.id %}" method="get">
  <div id="group-cols" class="btn-group btn-group-toggle" data-toggle="buttons">
    {% for name, checked in group_cols.items %}
    <label class="btn btn-outline-info">
      <input type="checkbox" name="groupCol" value="{{name}}" {% if checked %} checked {% endif %} autocomplete="off">
        {{ name }}
      </label>
      {% endfor %}
  </div>
</form>

{% if dataset %}
  <table class="table">
    <thead>
      <tr>
        {% for heading in dataset.header %}
        <th scope="col">{{heading}}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
        {% for row in dataset.records %}
        <tr>
          {% for value in row %}
          <td>{{value}}</td>
          {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% else %}
  <ul class="list-group">
    <li class="list-group-item">Sorry, no people in this list.</li>
  </ul>
{% endif %}

{% endblock %}


{% block script %}

$(document).ready(function() {
  var groupColsTimeout;
  $("#group-cols").click(function() {
    clearTimeout(groupColsTimeout);
    groupColsTimeout = setTimeout(function() {
      $("#groupForm").submit();
    }, 750);
  });
});

{% endblock %}

star_wars/people/templates/people/person_list.html
{% extends "people/base.html" %}

{% block title %} People Data Sets {% endblock %}

{% block content %}
<h1>{{dataset.created}}</h1>
{% if dataset %}
  <table class="table">
    <thead>
      <tr>
        {% for heading in dataset.header %}
        <th scope="col">
          <a href="{% url 'people:value_count' dataset.id %}?groupCol={{heading}}">{{heading}}</a>
        </th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
        {% for row in dataset.records %}
        <tr>
          {% for value in row %}
          <td>{{value}}</td>
          {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% if load_more_url %}
    <a class="btn btn-outline-primary" href="{{load_more_url}}" role="button">Load More</a>
  {% endif %}
{% else %}
  <ul class="list-group">
    <li class="list-group-item">Sorry, no people in this list.</li>
  </ul>
{% endif %}

{% endblock %}